package org.marc4j.rules;

import java.awt.Frame;
import java.io.File;

/**
 *
 * @author levenick
 */
public class BuildRegexesDialog extends javax.swing.JDialog {

    /**
     * Creates new form BuildRegexesDialog
     */
    public BuildRegexesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        doneButton.setVisible(false);
        setSize(400, 400);
    }

    public BuildRegexesDialog() {
        this(new Frame(), true);
        setTitle("BuildRegexesDialog");
        //this.requestFocus();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputLabel = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        outputFilenameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        outputLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        outputLabel.setText(".                                                        .");
        getContentPane().add(outputLabel);
        outputLabel.setBounds(20, 230, 350, 22);

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doneButton);
        doneButton.setBounds(150, 260, 77, 29);

        outputFilenameTF.setText("aaRegexes");
        outputFilenameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFilenameTFActionPerformed(evt);
            }
        });
        getContentPane().add(outputFilenameTF);
        outputFilenameTF.setBounds(120, 100, 160, 26);

        jLabel1.setText("output filename");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 80, 100, 16);

        jLabel2.setText("Type a different filename if you want.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 130, 250, 16);

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton);
        createButton.setBounds(140, 170, 97, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_doneButtonActionPerformed

    private void outputFilenameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFilenameTFActionPerformed
        doit();
    }//GEN-LAST:event_outputFilenameTFActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        doit();
    }//GEN-LAST:event_createButtonActionPerformed
    
    private void readItIn() {
        MyReader mr = new MyReader(Globals.getRootPath() + "patterns", true);
        if (mr.getFilename() == null) {
            return;
        }
        String outputFilename = outputFilenameTF.getText();
        String whereToPutIt = Globals.getRootPath() + "regexes" + File.separatorChar + outputFilename;
        int count = Utils.createRegexesFile(mr, whereToPutIt);
        outputLabel.setText("That file contained " + count + " lines.");
        outputLabel.setVisible(true);
    }

    private void doit() {
        readItIn();
        doneButton.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField outputFilenameTF;
    private javax.swing.JLabel outputLabel;
    // End of variables declaration//GEN-END:variables

}
