package org.marc4j.jrl.transformation;

import java.io.File;
import java.net.URL;
import org.marc4j.marc.Record;
import org.marc4j.rules.Rule;
import org.marc4j.rules.RuleSet;


/**
 * TransformationFrame.java created by levenick on May 16, 2014 at 9:45:55 AM
 */
public class TransformationFrame extends javax.swing.JFrame {

    public TransformationFrame() {  // 
        initComponents();
        setTitle("xform");
        setBounds(300,300,500,500);
        setVisible(true);
    }

    TransformationFrame(Record theRecord, RuleSet ruleList) {
        this();
        theTA.setText(theRecord.toString());
        ruleTA.setText(ruleList.toString());
    }
    
    public static void main(String[] args) {
        File f = new File(".");
        if (f.isDirectory()) {
            System.out.println("yes");
            File[] list = f.listFiles();
            for (File nextF: list) {
                System.out.println("nextF = " + nextF);
            }
        } else {
            System.out.println("no");
        }
        System.out.println("f = " + f);
        
        File foo = new File("resources");
        System.out.println("foo = " + foo);
        URL bar = Rule.class.getResource("resources/fileInfo.txt");
        System.out.println("bar = " + bar.getPath());
//        InputStream input = Rule.class.getResourceAsStream("resources/fileInfo.txt");
//        MyReader mr = new MyReader(input);
//        
//        System.out.println(mr.getFilename());
//        mr.close();
        
    }
    

    /** You can't modify the following code; it is regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        theTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ruleTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        theTA.setColumns(20);
        theTA.setRows(5);
        jScrollPane1.setViewportView(theTA);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        ruleTA.setColumns(20);
        ruleTA.setRows(5);
        jScrollPane2.setViewportView(ruleTA);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ruleTA;
    private javax.swing.JTextArea theTA;
    // End of variables declaration//GEN-END:variables

}